### ISSUE TITLE
Permission error with proms_predict

### ISSUE THREAD

**Issue by Chetson14** [bzhanglab/proms#4]
Hello and thank you for ProMS, 
I have successfully used ProMS for marker selection on proteomics data.  My problem is that prediction on other datasets always failed because of a permission error of a temp file (.yml).  

Any idea/solution to help me solve this problem?  Thank you in advance for your help.

C:\WINDOWS\system32>cd C:\Users\gagd2502\Desktop\DIAnn\Proms\env\Scripts
C:\Users\gagd2502\Desktop\DIAnn\Proms\env\Scripts>activate
(env) C:\Users\gagd2502\Desktop\DIAnn\Proms\env\Scripts>proms_train -f run_config_file.yml -d nec.yml
data config file: C:\Users\gagd2502\Desktop\DIAnn\Proms\env\Scripts\nec.yml
processing data ...
prediction type: cls
view: pro
train data target view features length 63
test data target view features length 63
common target view features length 63
number of samples: 90
test sample size: 91
k=22, repeat=1, estimator=lr, fs_method=proms
acc:0.9259, auroc: 0.9725
k=22, repeat=2, estimator=lr, fs_method=proms
acc:0.8889, auroc: 0.9286
………
k=22, repeat=1, estimator=lr, fs_method=proms
acc:0.967, auroc:0.984

**Everything is ok until this step**
(env) C:\Users\gagd2502\Desktop\DIAnn\Proms\env\Scripts>proms_predict -m results\2022_09_06_22_15_09\full_model\full_model.pkl -d Prediction_data\FreeSearch_1089entrees_reportpg2.tsv
Traceback (most recent call last):
  File "C:\Users\gagd2502\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\gagd2502\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\gagd2502\Desktop\DIAnn\Proms\env\Scripts\proms_predict.exe\__main__.py", line 9, in <module>
  File "c:\users\gagd2502\desktop\diann\proms\env\lib\site-packages\proms\predict.py", line 134, in main
    with open(temp.name, 'w') as fh:
**PermissionError: [Errno 13] Permission denied: 'C:\\Users\\gagd2502\\AppData\\Local\\Temp\\tmp_8vlaezi.yml'**

**Comment by zhiaos** [comment]
It is probably a Windows temp file related issue. I've uploaded a new version to pypi.  Can you try upgrading to version 1.0.6?

**Comment by Chetson14** [comment]
Hello again, thank you for the answer. 
I have upgraded to the new version of ProMS, but it returns a new error.  I have tried with the same file I have used to test data and another data file and it gave me the same error : 

(env) C:\Users\gagd2502\Desktop\DIAnn\Proms\env\Scripts>proms_predict -m results\2022_09_07_23_10_01\full_model\full_model.pkl -d Prediction_data\FreeSearch_1089entrees_reportpg2.tsv
Traceback (most recent call last):

  File "C:\Users\gagd2502\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\gagd2502\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\gagd2502\Desktop\DIAnn\Proms\env\Scripts\proms_predict.exe\__main__.py", line 7, in <module>
  File "C:\Users\gagd2502\Desktop\DIAnn\Proms\env\lib\site-packages\proms\predict.py", line 134, in main
    yaml.dump(config_dict, fh)
  File "C:\Users\gagd2502\Desktop\DIAnn\Proms\env\lib\site-packages\yaml\__init__.py", line 290, in dump
    return dump_all([data], stream, Dumper=Dumper, **kwds)
  File "C:\Users\gagd2502\Desktop\DIAnn\Proms\env\lib\site-packages\yaml\__init__.py", line 278, in dump_all
    dumper.represent(data)
  File "C:\Users\gagd2502\Desktop\DIAnn\Proms\env\lib\site-packages\yaml\representer.py", line 28, in represent
    self.serialize(node)
  File "C:\Users\gagd2502\Desktop\DIAnn\Proms\env\lib\site-packages\yaml\serializer.py", line 54, in serialize
    self.serialize_node(node, None, None)
  File "C:\Users\gagd2502\Desktop\DIAnn\Proms\env\lib\site-packages\yaml\serializer.py", line 108, in serialize_node
    self.serialize_node(value, node, key)
  File "C:\Users\gagd2502\Desktop\DIAnn\Proms\env\lib\site-packages\yaml\serializer.py", line 107, in serialize_node
    self.serialize_node(key, node, None)
  File "C:\Users\gagd2502\Desktop\DIAnn\Proms\env\lib\site-packages\yaml\serializer.py", line 90, in serialize_node
    style=node.style))
  File "C:\Users\gagd2502\Desktop\DIAnn\Proms\env\lib\site-packages\yaml\emitter.py", line 115, in emit
    self.state()
  File "C:\Users\gagd2502\Desktop\DIAnn\Proms\env\lib\site-packages\yaml\emitter.py", line 393, in expect_first_block_mapping_key
    return self.expect_block_mapping_key(first=True)
  File "C:\Users\gagd2502\Desktop\DIAnn\Proms\env\lib\site-packages\yaml\emitter.py", line 403, in expect_block_mapping_key
    self.expect_node(mapping=True, simple_key=True)
  File "C:\Users\gagd2502\Desktop\DIAnn\Proms\env\lib\site-packages\yaml\emitter.py", line 244, in expect_node
    self.expect_scalar()
  File "C:\Users\gagd2502\Desktop\DIAnn\Proms\env\lib\site-packages\yaml\emitter.py", line 268, in expect_scalar
    self.process_scalar()
  File "C:\Users\gagd2502\Desktop\DIAnn\Proms\env\lib\site-packages\yaml\emitter.py", line 533, in process_scalar
    self.write_plain(self.analysis.scalar, split)
  File "C:\Users\gagd2502\Desktop\DIAnn\Proms\env\lib\site-packages\yaml\emitter.py", line 1132, in write_plain
    self.stream.write(data)
  File "C:\Users\gagd2502\AppData\Local\Programs\Python\Python37\lib\tempfile.py", line 481, in func_wrapper
    return func(*args, **kwargs)
TypeError: a bytes-like object is required, not 'str'

David

**Comment by zhiaos** [comment]
can you update the package again? I made another change.

**Comment by Chetson14** [comment]
Predictions are working fine with the latest version! Thank you very much for your help, and looking forward to citing your great work in a future publication!

**Comment by zhiaos** [comment]
glad to hear it is working.
